/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useState, useEffect, useContext } from 'react';

const translations = {
    en: {
        // Header
        menu: "Menu",
        ourStory: "Our Story",
        visitUs: "Visit Us",
        order: "Order",
        logout: "Logout",
        
        // Hero
        heroBadgeText: "✦ Crafted Fresh Every Day",
        heroTitle1: "Taste the ",
        heroTitleHighlight: "Desi Fizz",
        heroTitle2: " of India",
        heroSubtitle: "Authentic masala sodas, sharbat fizz, and street-style sparkling drinks — the flavours of India in every sip. 🇮🇳",
        exploreMenu: "Explore Menu",
        sodaRecipes: "Soda Recipes",
        desiSpices: "Desi Spices",
        rating: "Rating",
        handcraftedFresh: "Handcrafted Fresh",
        realIndianSpices: "Real Indian Spices",
        
        // MenuGrid
        whatWeOffer: "✦ What We Offer",
        ourMenuTitle1: "Our ",
        ourMenuTitle2: "Menu",
        menuSubtitle: "India's most flavourful soda bar — pick your size, pick your vibe 🇮🇳",
        noItems: "No items in this category yet.",
        
        // Categories
        "Regular Soda": "Regular Soda",
        "Special Soda": "Special Soda",
        "Mojito": "Mojito",
        "Sheng Soda": "Sheng Soda",
        "Moctails": "Moctails",
        "Soda Short": "Soda Short",
        "Ice Cream Soda": "Ice Cream Soda",
        "Softy Ice Cream": "Softy Ice Cream",
        "Cold Coffee": "Cold Coffee",
        
        // Items
        "Mango (Juice)": "Mango (Juice)",
        "Pineapple (Juice)": "Pineapple (Juice)",
        "Orange": "Orange",
        "Fruit Beer": "Fruit Beer",
        "Whisky": "Whisky",
        "Vodka": "Vodka",
        "Rum": "Rum",
        "Masala Soda": "Masala Soda",
        "Blue Berry": "Blue Berry",
        "Kala Khatta": "Kala Khatta",
        "Pudina Masala": "Pudina Masala",
        "Lemon Up": "Lemon Up",
        "Cola Premium": "Cola Premium",
        "Kiwi": "Kiwi",
        "Jamfal Red (Guava)": "Jamfal Red (Guava)",
        "Redbull": "Redbull",
        "Green Apple": "Green Apple",
        "Litchi": "Litchi",
        "Mountain Dew": "Mountain Dew",
        "Diet Coke": "Diet Coke",
        "Pepsi": "Pepsi",
        "Strawberry": "Strawberry",
        "Monster Energy": "Monster Energy",
        "Prime Hydration (Ice Pop)": "Prime Hydration (Ice Pop)",
        "Prime Hydration (Lemon & Mint)": "Prime Hydration (Lemon & Mint)",
        "Prime Hydration (Blue Raspberry)": "Prime Hydration (Blue Raspberry)",
        "Prime Hydration (Cherry Freeze)": "Prime Hydration (Cherry Freeze)",
        "Special Mango": "Special Mango",
        "Special Litchi": "Special Litchi",
        "Special Green Apple": "Special Green Apple",
        "Special Jamfal": "Special Jamfal",
        "Special Kiwi": "Special Kiwi",
        "Special Pudina": "Special Pudina",
        "Special Lemon": "Special Lemon",
        "Special Blue Berry": "Special Blue Berry",
        "Special Orange": "Special Orange",
        "Special Pineapple": "Special Pineapple",
        "Special Strawberry": "Special Strawberry",
        "Special Rose Soda": "Special Rose Soda",
        "Special Jeera": "Special Jeera",
        "Jeera Shikanji": "Jeera Shikanji",
        "Lemon Shikanji": "Lemon Shikanji",
        "Special Watermelon": "Special Watermelon",
        "Kokam Soda": "Kokam Soda",
        "Blue Berry Mojito": "Blue Berry Mojito",
        "Pudina (Mint) Mojito": "Pudina (Mint) Mojito",
        "Lemon Mojito": "Lemon Mojito",
        "Virgin Mojito": "Virgin Mojito",
        "Strawberry Mojito": "Strawberry Mojito",
        "Orange Mojito": "Orange Mojito",
        "Kiwi Mojito": "Kiwi Mojito",
        "Green Apple Mojito": "Green Apple Mojito",
        "Jamfal Mojito": "Jamfal Mojito",
        "Litchi Mojito": "Litchi Mojito",
        "Kala Khatta Mojito": "Kala Khatta Mojito",
        "Rose Mojito": "Rose Mojito",
        "Watermelon Mojito": "Watermelon Mojito",
        "Blue Berry Sheng Soda": "Blue Berry Sheng Soda",
        "Pudina Sheng Soda": "Pudina Sheng Soda",
        "Masala Sheng Soda": "Masala Sheng Soda",
        "Orange Sheng Soda": "Orange Sheng Soda",
        "Kiwi Sheng Soda": "Kiwi Sheng Soda",
        "Green Apple Sheng Soda": "Green Apple Sheng Soda",
        "Jamfal Sheng Soda": "Jamfal Sheng Soda",
        "Litchi Sheng Soda": "Litchi Sheng Soda",
        "Kala Khatta Sheng Soda": "Kala Khatta Sheng Soda",
        "Gravity Sheng Soda": "Gravity Sheng Soda",
        "Galaxy Sheng Soda": "Galaxy Sheng Soda",
        "Gravity": "Gravity",
        "Galaxy": "Galaxy",
        "Flash Mountain": "Flash Mountain",
        "Flash Moctail": "Flash Moctail",
        "Pappins Moctail": "Pappins Moctail",
        "Bubble Berry": "Bubble Berry",
        "Grape Fantasy": "Grape Fantasy",
        "Urban Up Moctail": "Urban Up Moctail",
        "Goosebumps Moctail": "Goosebumps Moctail",
        "Flash Berry Moctail": "Flash Berry Moctail",
        "Fernet Libre": "Fernet Libre",
        "Something Blue": "Something Blue",
        "Fat Frog": "Fat Frog",
        "Barbie Moctail": "Barbie Moctail",
        "Blue Sky": "Blue Sky",
        "Bloody Jack": "Bloody Jack",
        "Frozen": "Frozen",
        "Deep Throat": "Deep Throat",
        "Paradise": "Paradise",
        "Gin & Tonic": "Gin & Tonic",
        "Sidecar": "Sidecar",
        "Black Water": "Black Water",
        "Mini 6": "Mini 6",
        "M6 Moctail": "M6 Moctail",
        "Green Zone": "Green Zone",
        "Red Zone": "Red Zone",
        "Lime Ice Tea": "Lime Ice Tea",
        "Peach Ice Tea": "Peach Ice Tea",
        "Bloody Mary": "Bloody Mary",
        "Purple Star": "Purple Star",
        "Destroyer": "Destroyer",
        "Luffy": "Luffy",
        "Lebron": "Lebron",
        "The Seven": "The Seven",
        "Avatar Moctail": "Avatar Moctail",
        "Hellfire": "Hellfire",
        "Delux": "Delux",
        "Red Dead": "Red Dead",
        "Maleficent Ice Tea": "Maleficent Ice Tea",
        "Rock Well": "Rock Well",
        "Fuji 6": "Fuji 6",
        "Happy Day": "Happy Day",
        "Dutch Bros": "Dutch Bros",
        "Coastal Dive": "Coastal Dive",
        "Fountain": "Fountain",
        "Mango + Vanilla": "Mango + Vanilla",
        "Orange + Vanilla": "Orange + Vanilla",
        "Blue Berry + Vanilla": "Blue Berry + Vanilla",
        "Kala Khatta + Vanilla": "Kala Khatta + Vanilla",
        "Pineapple + Vanilla": "Pineapple + Vanilla",
        "Cola Premium + Vanilla": "Cola Premium + Vanilla",
        "Kiwi + Vanilla": "Kiwi + Vanilla",
        "Jamfal Red + Vanilla": "Jamfal Red + Vanilla",
        "Green Apple + Vanilla": "Green Apple + Vanilla",
        "Litchi + Vanilla": "Litchi + Vanilla",
        "Flash Moctail + Vanilla": "Flash Moctail + Vanilla",
        "Gravity + Vanilla": "Gravity + Vanilla",
        "Galaxy + Vanilla": "Galaxy + Vanilla",
        "Green Zone + Vanilla": "Green Zone + Vanilla",
        "Red Zone + Vanilla": "Red Zone + Vanilla",
        "Lime Ice Tea + Vanilla": "Lime Ice Tea + Vanilla",
        "Peach Ice Tea + Vanilla": "Peach Ice Tea + Vanilla",
        "Avatar Moctail + Vanilla": "Avatar Moctail + Vanilla",
        "Barbie Moctail + Vanilla": "Barbie Moctail + Vanilla",
        "Purple Star + Vanilla": "Purple Star + Vanilla",
        "Flash Mountain + Vanilla": "Flash Mountain + Vanilla",
        "Chocolate": "Chocolate",
        "Vanilla": "Vanilla",
        "Choco & Vanilla Mix": "Choco & Vanilla Mix",
        "Chocolate Dip Softy": "Chocolate Dip Softy",
        "Vanilla Dip Softy": "Vanilla Dip Softy",
        "Choco & Vanilla Mix Dip": "Choco & Vanilla Mix Dip",
        "Dark Choco Dip Softy": "Dark Choco Dip Softy",
        "Wafer Softy": "Wafer Softy",
        "Cold Coffee (Chocolate)": "Cold Coffee (Chocolate)",

        // MenuItemCard
        added: "✓ Added!",
        addOrder: "+ Order",
        
        // Footer
        ourPromise1: "Our ",
        ourPromise2: "Promise",
        promiseText: "Every fizzy creation at Fizztaa is handcrafted with authentic Indian spices, fresh seasonal produce, and techniques passed down through generations. Pure ingredients. Pure joy. Pure India. 🇮🇳",
        getToKnowUs: "Get to Know Us",
        footerSubtitle: "India's favourite sparkling soda bar — crafted fresh, served with love.",
        info: "Info",
        franchise: "Franchise",
        contact: "Contact",
        copyright: "© 2026 Fizztaa Soda Co. Made with ❤️ in India.",
        privacyPolicy: "Privacy Policy",
        termsOfUse: "Terms of Use",
        fssaiInfo: "FSSAI Info",
        
        // Auth
        signIn: "Sign In",
        signUp: "Sign Up",
        fullName: "Full Name",
        phone: "Mobile Number",
        email: "Email Address",
        password: "Password",
        dontHaveAccount: "Don't have an account?",
        alreadyHaveAccount: "Already have an account?",
        welcomeBack: "Welcome Back!",
        createAccount: "Create Account",
        loginSuccess: "Logged in successfully!",
        signupSuccess: "Account created successfully!",
        logoutSuccess: "Logged out successfully!",
        signToOrder: "Sign in to Place Order",
        editProfile: "Edit Profile",
        saveChanges: "Save Changes",
        profileUpdateSuccess: "Profile updated successfully!",
        
        // Orders
        myCart: "My Cart",
        orderHistory: "Order History",
        orderId: "Order ID",
        status: "Status",
        date: "Date",
        noOrdersYet: "No orders yet",
        orderReceived: "Order Received",
        preparing: "Preparing your Fizz",
        outForDelivery: "Out for Delivery",
        delivered: "Delivered"
    },
    hi: {
        // Header
        menu: "मेनू",
        ourStory: "हमारी कहानी",
        visitUs: "संपर्क करें",
        order: "ऑर्डर करें",
        logout: "लॉग आउट",
        
        // Hero
        heroBadgeText: "✦ हर दिन ताज़ा तैयार",
        heroTitle1: "भारत के ",
        heroTitleHighlight: "देशी फिज़",
        heroTitle2: " का स्वाद लें",
        heroSubtitle: "प्रामाणिक मसाला सोडा, शरबत फिज़ और स्ट्रीट-स्टाइल स्पार्कलिंग ड्रिंक्स — हर घूंट में भारत के स्वाद। 🇮🇳",
        exploreMenu: "मेनू देखें",
        sodaRecipes: "सोडा रेसिपीज़",
        desiSpices: "देशी मसाले",
        rating: "रेटिंग",
        handcraftedFresh: "ताज़ा हस्तनिर्मित",
        realIndianSpices: "असली भारतीय मसाले",
        
        // MenuGrid
        whatWeOffer: "✦ हमारी पेशकश",
        ourMenuTitle1: "हमारा ",
        ourMenuTitle2: "मेनू",
        menuSubtitle: "भारत का सबसे स्वादिष्ट सोडा बार — अपना आकार चुनें, अपना मज़ा चुनें 🇮🇳",
        noItems: "इस श्रेणी में अभी कोई आइटम नहीं है।",
        
        // Categories
        "Regular Soda": "रेगुलर सोडा",
        "Special Soda": "स्पेशल सोडा",
        "Mojito": "मोजिटो",
        "Sheng Soda": "शेंग सोडा",
        "Moctails": "मॉकटेल",
        "Soda Short": "सोडा शॉर्ट",
        "Ice Cream Soda": "आइसक्रीम सोडा",
        "Softy Ice Cream": "सॉफ्टी आइसक्रीम",
        "Cold Coffee": "कोल्ड कॉफी",
        
        // Items
        "Mango (Juice)": "मैंगो (जूस)",
        "Pineapple (Juice)": "अनानास (जूस)",
        "Orange": "संतरा",
        "Fruit Beer": "फ्रूट बीयर",
        "Whisky": "व्हिस्की",
        "Vodka": "वोदका",
        "Rum": "रम",
        "Masala Soda": "मसाला सोडा",
        "Blue Berry": "ब्लू बेरी",
        "Kala Khatta": "काला खट्टा",
        "Pudina Masala": "पुदीना मसाला",
        "Lemon Up": "लेमन अप",
        "Cola Premium": "कोला प्रीमियम",
        "Kiwi": "कीवी",
        "Jamfal Red (Guava)": "जामफल रेड (अमरूद)",
        "Redbull": "रेडबुल",
        "Green Apple": "ग्रीन एप्पल",
        "Litchi": "लीची",
        "Mountain Dew": "माउंटेन ड्यू",
        "Diet Coke": "डाइट कोक",
        "Pepsi": "पेप्सी",
        "Strawberry": "स्ट्रॉबेरी",
        "Monster Energy": "मॉन्स्टर एनर्जी",
        "Prime Hydration (Ice Pop)": "प्राइम हाइड्रेशन (आइस पॉप)",
        "Prime Hydration (Lemon & Mint)": "प्राइम हाइड्रेशन (नींबू और मिंट)",
        "Prime Hydration (Blue Raspberry)": "प्राइम हाइड्रेशन (ब्लू रास्पबेरी)",
        "Prime Hydration (Cherry Freeze)": "प्राइम हाइड्रेशन (चेरी फ्रीज)",
        "Special Mango": "स्पेशल मैंगो",
        "Special Litchi": "स्पेशल लीची",
        "Special Green Apple": "स्पेशल ग्रीन एप्पल",
        "Special Jamfal": "स्पेशल Jamfal",
        "Special Kiwi": "स्पेशल कीवी",
        "Special Pudina": "स्पेशल पुदीना",
        "Special Lemon": "स्पेशल नींबू",
        "Special Blue Berry": "स्पेशल ब्लू बेरी",
        "Special Orange": "स्पेशल संतरा",
        "Special Pineapple": "स्पेशल अनानास",
        "Special Strawberry": "स्पेशल स्ट्रॉबेरी",
        "Special Rose Soda": "स्पेशल रोज़ सोडा",
        "Special Jeera": "स्पेशल जीरा",
        "Jeera Shikanji": "जीरा शिकंजी",
        "Lemon Shikanji": "नींबू शिकंजी",
        "Special Watermelon": "स्पेशल तरबूज",
        "Kokam Soda": "कोकम सोडा",
        "Blue Berry Mojito": "ब्लू बेरी मोजिटो",
        "Pudina (Mint) Mojito": "पुदीना (पुदीना) मोजिटो",
        "Lemon Mojito": "नींबू मोजिटो",
        "Virgin Mojito": "वर्जिन मोजिटो",
        "Strawberry Mojito": "स्ट्रॉबेरी मोजिटो",
        "Orange Mojito": "संतरा मोजिटो",
        "Kiwi Mojito": "कीवी मोजिटो",
        "Green Apple Mojito": "ग्रीन एप्पल मोजिटो",
        "Jamfal Mojito": "Jamfal मोजिटो",
        "Litchi Mojito": "लीची मोजिटो",
        "Kala Khatta Mojito": "काला खट्टा मोजिटो",
        "Rose Mojito": "Rose मोजिटो",
        "Watermelon Mojito": "तरबूज मोजिटो",
        "Blue Berry Sheng Soda": "ब्लू बेरी शेंग सोडा",
        "Pudina Sheng Soda": "पुदीना शेंग सोडा",
        "Masala Sheng Soda": "Masala शेंग सोडा",
        "Orange Sheng Soda": "संतरा शेंग सोडा",
        "Kiwi Sheng Soda": "कीवी शेंग सोडा",
        "Green Apple Sheng Soda": "ग्रीन एप्पल शेंग सोडा",
        "Jamfal Sheng Soda": "Jamfal शेंग सोडा",
        "Litchi Sheng Soda": "लीची शेंग सोडा",
        "Kala Khatta Sheng Soda": "काला खट्टा शेंग सोडा",
        "Gravity Sheng Soda": "ग्रेविटी शेंग सोडा",
        "Galaxy Sheng Soda": "गैलेक्सी शेंग सोडा",
        "Gravity": "ग्रेविटी",
        "Galaxy": "गैलेक्सी",
        "Flash Mountain": "फ्लैश माउंटेन",
        "Flash Moctail": "फ्लैश मॉकटेल",
        "Pappins Moctail": "पैपिन्स मॉकटेल",
        "Bubble Berry": "बबल बेरी",
        "Grape Fantasy": "अंगूर फैंटेसी",
        "Urban Up Moctail": "अर्बन अप मॉकटेल",
        "Goosebumps Moctail": "गूसबंप्स मॉकटेल",
        "Flash Berry Moctail": "फ्लैश बेरी मॉकटेल",
        "Fernet Libre": "फर्नेट लिब्रे",
        "Something Blue": "समथिंग ब्लू",
        "Fat Frog": "फैट फ्रॉग",
        "Barbie Moctail": "बार्बी मॉकटेल",
        "Blue Sky": "ब्लू स्काई",
        "Bloody Jack": "ब्लडी जैक",
        "Frozen": "फ्रोज़न",
        "Deep Throat": "डीप थ्रोट",
        "Paradise": "पैराडाइज़",
        "Gin & Tonic": "जिन एंड टॉनिक",
        "Sidecar": "साइडकार",
        "Black Water": "ब्लैक वाटर",
        "Mini 6": "मिनी 6",
        "M6 Moctail": "M6 मॉकटेल",
        "Green Zone": "ग्रीन ज़ोन",
        "Red Zone": "रेड ज़ोन",
        "Lime Ice Tea": "लाइम आइस टी",
        "Peach Ice Tea": "पीच आइस टी",
        "Bloody Mary": "ब्लडी मैरी",
        "Purple Star": "पर्पल स्टार",
        "Destroyer": "डिस्ट्रॉयर",
        "Luffy": "लफी",
        "Lebron": "लेब्रोन",
        "The Seven": "द सेवन",
        "Avatar Moctail": "अवतार मॉकटेल",
        "Hellfire": "हेलफायर",
        "Delux": "डीलक्स",
        "Red Dead": "रेड डेड",
        "Maleficent Ice Tea": "मेलिफिसेंट आइस टी",
        "Rock Well": "रॉक वेल",
        "Fuji 6": "फ़ूजी 6",
        "Happy Day": "हैप्पी डे",
        "Dutch Bros": "डच ब्रोस",
        "Coastal Dive": "कोस्टल डाइव",
        "Fountain": "फाउंटेन",
        "Mango + Vanilla": "मैंगो + वैनिला",
        "Orange + Vanilla": "संतरा + वैनिला",
        "Blue Berry + Vanilla": "ब्लू बेरी + वैनिला",
        "Kala Khatta + Vanilla": "काला खट्टा + वैनिला",
        "Pineapple + Vanilla": "अनानास + वैनिला",
        "Cola Premium + Vanilla": "कोला प्रीमियम + वैनिला",
        "Kiwi + Vanilla": "कीवी + वैनिला",
        "Jamfal Red + Vanilla": "जामफल रेड + वैनिला",
        "Green Apple + Vanilla": "ग्रीन एप्पल + वैनिला",
        "Litchi + Vanilla": "लीची + वैनिला",
        "Flash Moctail + Vanilla": "फ्लैश मॉकटेल + वैनिला",
        "Gravity + Vanilla": "ग्रेविटी + वैनिला",
        "Galaxy + Vanilla": "गैलेक्सी + वैनिला",
        "Green Zone + Vanilla": "ग्रीन ज़ोन + वैनिला",
        "Red Zone + Vanilla": "रेड ज़ोन + वैनिला",
        "Lime Ice Tea + Vanilla": "लाइम आइस टी + वैनिला",
        "Peach Ice Tea + Vanilla": "पीच आइस टी + वैनिला",
        "Avatar Moctail + Vanilla": "अवतार मॉकटेल + वैनिला",
        "Barbie Moctail + Vanilla": "बार्बी मॉकटेल + वैनिला",
        "Purple Star + Vanilla": "पर्पल स्टार + वैनिला",
        "Flash Mountain + Vanilla": "फ्लैश माउंटेन + वैनिला",
        "Chocolate": "चॉकलेट",
        "Vanilla": "वैनिला",
        "Choco & Vanilla Mix": "चोको और वैनिला मिक्स",
        "Chocolate Dip Softy": "चॉकलेट Dip Softy",
        "Vanilla Dip Softy": "वैनिला डिप सॉफ्टी",
        "Choco & Vanilla Mix Dip": "चोको और वैनिला मिक्स डिप",
        "Dark Choco Dip Softy": "डार्क चोको डिप सॉफ्टी",
        "Wafer Softy": "वेफर सॉफ्टी",
        "Cold Coffee (Chocolate)": "कोल्ड कॉफी (चॉकलेट)",

        // MenuItemCard
        added: "✓ जुड़ गया!",
        addOrder: "+ ऑर्डर",
        
        // Footer
        ourPromise1: "हमारा ",
        ourPromise2: "वादा",
        promiseText: "फ़िज़्टा में हर फ़िजी ड्रिंक प्रामाणिक भारतीय मसालों, ताज़े मौसमी उत्पादों और पीढ़ियों से चली आ रही तकनीकों के साथ तैयार किया जाता है। शुद्ध सामग्री। शुद्ध आनंद। शुद्ध भारत। 🇮🇳",
        getToKnowUs: "हमारे बारे में जानें",
        footerSubtitle: "भारत का पसंदीदा स्पार्कलिंग सोडा बार - ताज़ा बनाया गया, प्यार से परोसा गया।",
        info: "जानकारी",
        franchise: "फ्रेंचाइजी",
        contact: "संपर्क",
        copyright: "© 2026 फ़िज़्टा सोडा कंपनी। ❤️ भारत में निर्मित।",
        privacyPolicy: "गोपनीयता नीति",
        termsOfUse: "उपयोग की शर्तें",
        fssaiInfo: "FSSAI जानकारी",
        
        // Auth
        signIn: "लॉग इन करें",
        signUp: "साइन अप करें",
        fullName: "पूरा नाम",
        phone: "मोबाइल नंबर",
        email: "ईमेल पता",
        password: "पासवर्ड",
        dontHaveAccount: "खाता नहीं है?",
        alreadyHaveAccount: "पहले से खाता है?",
        welcomeBack: "वापसी पर स्वागत है!",
        createAccount: "खाता बनाएँ",
        loginSuccess: "सफलतापूर्वक लॉग इन किया गया!",
        signupSuccess: "खाता सफलतापूर्वक बनाया गया!",
        logoutSuccess: "सफलतापूर्वक लॉग आउट किया गया!",
        signToOrder: "ऑर्डर करने के लिए लॉग इन करें",
        editProfile: "प्रोफ़ाइल संपादित करें",
        saveChanges: "बदलाव सहेजें",
        profileUpdateSuccess: "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!",
        
        // Orders
        myCart: "मेरी कार्ट",
        orderHistory: "ऑर्डर इतिहास",
        orderId: "ऑर्डर आईडी",
        status: "स्थिति",
        date: "तारीख",
        noOrdersYet: "अभी तक कोई ऑर्डर नहीं",
        orderReceived: "ऑर्डर प्राप्त हुआ",
        preparing: "आपका फ़िज़ तैयार हो रहा है",
        outForDelivery: "डिलीवरी के लिए बाहर",
        delivered: "वितरित"
    },
    mr: {
        "menu": "मेन्यू",
        "ourStory": "आमची कथा",
        "visitUs": "भेट द्या",
        "order": "ऑर्डर",
        "logout": "लॉग आउट",
        
        // Hero
        "heroBadgeText": "✦ रोज ताजे बनवलेले",
        "heroTitle1": "भारताचा ",
        "heroTitleHighlight": "देशी फिझ",
        "heroTitle2": " चा आस्वाद घ्या",
        "heroSubtitle": "अस्सल मसाला सोडा, सरबत फिझ आणि स्ट्रीट-स्टाईल स्पार्कलिंग ड्रिंक्स — प्रत्येक घोटासोबत भारताची चव. 🇮🇳",
        "exploreMenu": "मेन्यू पहा",
        "sodaRecipes": "सोडा रेसिपी",
        "desiSpices": "देशी मसाले",
        "rating": "रेटिंग",
        "handcraftedFresh": "ताजे हस्तनिर्मित",
        "realIndianSpices": "अस्सल भारतीय मसाले",
        "whatWeOffer": "✦ आमची ऑफर",
        "ourMenuTitle1": "आमचा ",
        "ourMenuTitle2": "मेन्यू",
        "menuSubtitle": "भारतातील सर्वात चविष्ट सोडा बार — तुमचा आकार निवडा, मजा निवडा 🇮🇳",
        "noItems": "या श्रेणीत अद्याप कोणतीही आयटम नाहीत.",
        "Regular Soda": "रेग्युलर सोडा",
        "Special Soda": "स्पेशल सोडा",
        "Mojito": "मोजिटो",
        "Sheng Soda": "शेंग सोडा",
        "Moctails": "मॉकटेल्स",
        "Soda Short": "सोडा शॉर्ट",
        "Ice Cream Soda": "आईस्क्रीम सोडा",
        "Softy Ice Cream": "सॉफ्टी आईस्क्रीम",
        "Cold Coffee": "कोल्ड कॉफी",
        "Mango (Juice)": "मँगो (ज्यूस)",
        "Pineapple (Juice)": "अननस (ज्यूस)",
        "Orange": "संत्रा",
        "Fruit Beer": "फ्रूट बिअर",
        "Whisky": "व्हिस्की",
        "Vodka": "व्होडका",
        "Rum": "रम",
        "Masala Soda": "मसाला सोडा",
        "Blue Berry": "ब्लू बेरी",
        "Kala Khatta": "काला खट्टा",
        "Pudina Masala": "पुदिना मसाला",
        "Lemon Up": "लेमन अप",
        "Cola Premium": "कोला प्रीमियम",
        "Kiwi": "किवी",
        "Jamfal Red (Guava)": "जांभई रेड (पेरू)",
        "Redbull": "रेडबुल",
        "Green Apple": "ग्रीन एप्पल",
        "Litchi": "लिची",
        "Mountain Dew": "माउंटन ड्यू",
        "Diet Coke": "डाएट कोक",
        "Pepsi": "पेप्सी",
        "Strawberry": "स्ट्रॉबेरी",
        "Monster Energy": "मॉन्स्टर एनर्जी",
        "Prime Hydration (Ice Pop)": "प्राइम हायड्रेशन (आईस पॉप)",
        "Prime Hydration (Lemon & Mint)": "प्राइम हायड्रेशन (लिंबू आणि मिंट)",
        "Prime Hydration (Blue Raspberry)": "प्राइम हायड्रेशन (ब्लू रास्पबेरी)",
        "Prime Hydration (Cherry Freeze)": "प्राइम हायड्रेशन (चेरी फ्रीझ)",
        "Special Mango": "स्पेशल मँगो",
        "Special Litchi": "स्पेशल लिची",
        "Special Green Apple": "स्पेशल ग्रीन एप्पल",
        "Special Jamfal": "स्पेशल जांभई",
        "Special Kiwi": "स्पेशल किवी",
        "Special Pudina": "स्पेशल पुदिना",
        "Special Lemon": "स्पेशल लिंबू",
        "Special Blue Berry": "स्पेशल ब्लू बेरी",
        "Special Orange": "स्पेशल संत्रा",
        "Special Pineapple": "स्पेशल अननस",
        "Special Strawberry": "स्पेशल स्ट्रॉबेरी",
        "Special Rose Soda": "स्पेशल रोज सोडा",
        "Special Jeera": "स्पेशल जिरा",
        "Jeera Shikanji": "जिरा शिकंजी",
        "Lemon Shikanji": "लिंबू शिकंजी",
        "Special Watermelon": "स्पेशल कलिंगड",
        "Kokam Soda": "कोकम सोडा",
        "Blue Berry Mojito": "ब्लू बेरी मोजिटो",
        "Pudina (Mint) Mojito": "पुदिना (मिंट) मोजिटो",
        "Lemon Mojito": "लिंबू मोजिटो",
        "Virgin Mojito": "व्हर्जिन मोजिटो",
        "Strawberry Mojito": "स्ट्रॉबेरी मोजिटो",
        "Orange Mojito": "संत्रा मोजिटो",
        "Kiwi Mojito": "किवी मोजिटो",
        "Green Apple Mojito": "ग्रीन एप्पल मोजिटो",
        "Jamfal Mojito": "जांभई मोजिटो",
        "Litchi Mojito": "लिची मोजिटो",
        "Kala Khatta Mojito": "काला खट्टा मोजिटो",
        "Rose Mojito": "रोज मोजिटो",
        "Watermelon Mojito": "कलिंगड मोजिटो",
        "Blue Berry Sheng Soda": "ब्लू बेरी शेंग सोडा",
        "Pudina Sheng Soda": "पुदिना शेंग सोडा",
        "Masala Sheng Soda": "मसाला शेंग सोडा",
        "Orange Sheng Soda": "संत्रा शेंग सोडा",
        "Kiwi Sheng Soda": "किवी शेंग सोडा",
        "Green Apple Sheng Soda": "ग्रीन एप्पल शेंग सोडा",
        "Jamfal Sheng Soda": "जांभई शेंग सोडा",
        "Litchi Sheng Soda": "लिची शेंग सोडा",
        "Kala Khatta Sheng Soda": "काला खट्टा शेंग सोडा",
        "Gravity Sheng Soda": "ग्रॅविटी शेंग सोडा",
        "Galaxy Sheng Soda": "गॅलेक्सी शेंग सोडा",
        "Gravity": "ग्रॅविटी",
        "Galaxy": "गॅलेक्सी",
        "Flash Mountain": "फ्लॅश माउंटन",
        "Flash Moctail": "फ्लॅश मॉकटेल",
        "Pappins Moctail": "पॅपिन्स मॉकटेल",
        "Bubble Berry": "बबल बेरी",
        "Grape Fantasy": "ग्रेप फँटसी",
        "Urban Up Moctail": "अर्बन अप मॉकटेल",
        "Goosebumps Moctail": "गुजबंप्स मॉकटेल",
        "Flash Berry Moctail": "फ्लॅश बेरी मॉकटेल",
        "Fernet Libre": "फर्नेट लिब्रे",
        "Something Blue": "समथिंग ब्लू",
        "Fat Frog": "फॅट फ्रॉग",
        "Barbie Moctail": "बार्बी मॉकटेल",
        "Blue Sky": "ब्लू स्काय",
        "Bloody Jack": "ब्लडी जॅक",
        "Frozen": "फ्रोजन",
        "Deep Throat": "डीप थ्रोट",
        "Paradise": "पॅराडाईज",
        "Gin & Tonic": "जिन आणि टॉनिक",
        "Sidecar": "साईडकार",
        "Black Water": "ब्लॅक वॉटर",
        "Mini 6": "मिनी 6",
        "M6 Moctail": "M6 मॉकटेल",
        "Green Zone": "ग्रीन झोन",
        "Red Zone": "रेड झोन",
        "Lime Ice Tea": "लाइम आईस टी",
        "Peach Ice Tea": "पीच आईस टी",
        "Bloody Mary": "ब्लडी मेरी",
        "Purple Star": "पर्पल स्टार",
        "Destroyer": "डिस्ट्रॉयर",
        "Luffy": "लुफी",
        "Lebron": "लेब्रॉन",
        "The Seven": "द सेव्हन",
        "Avatar Moctail": "अवतार मॉकटेल",
        "Hellfire": "हेलफायर",
        "Delux": "डिलक्स",
        "Red Dead": "रेड डेड",
        "Maleficent Ice Tea": "मॅलेफिसेंट आईस टी",
        "Rock Well": "रॉक वेल",
        "Fuji 6": "फुजी 6",
        "Happy Day": "हॅपी डे",
        "Dutch Bros": "डच ब्रदर्स",
        "Coastal Dive": "कोस्टल डाईव्ह",
        "Fountain": "फाउंटन",
        "Mango + Vanilla": "मँगो + व्हॅनिला",
        "Orange + Vanilla": "संत्रा + व्हॅनिला",
        "Blue Berry + Vanilla": "ब्लू बेरी + व्हॅनिला",
        "Kala Khatta + Vanilla": "काला खट्टा + व्हॅनिला",
        "Pineapple + Vanilla": "अननस + व्हॅनिला",
        "Cola Premium + Vanilla": "कोला प्रीमियम + व्हॅनिला",
        "Kiwi + Vanilla": "किवी + व्हॅनिला",
        "Jamfal Red + Vanilla": "जांभई रेड + व्हॅनिला",
        "Green Apple + Vanilla": "ग्रीन एप्पल + व्हॅनिला",
        "Litchi + Vanilla": "लिची + व्हॅनिला",
        "Flash Moctail + Vanilla": "फ्लॅश मॉकटेल + व्हॅनिला",
        "Gravity + Vanilla": "ग्रॅविटी + व्हॅनिला",
        "Galaxy + Vanilla": "गॅलेक्सी + व्हॅनिला",
        "Green Zone + Vanilla": "ग्रीन झोन + व्हॅनिला",
        "Red Zone + Vanilla": "रेड झोन + व्हॅनिला",
        "Lime Ice Tea + Vanilla": "लाइम आईस टी + व्हॅनिला",
        "Peach Ice Tea + Vanilla": "पीच आईस टी + व्हॅनिला",
        "Avatar Moctail + Vanilla": "अवतार मॉकटेल + व्हॅनिला",
        "Barbie Moctail + Vanilla": "बार्बी मॉकटेल + व्हॅनिला",
        "Purple Star + Vanilla": "पर्पल स्टार + व्हॅनिला",
        "Flash Mountain + Vanilla": "फ्लॅश माउंटन + व्हॅनिला",
        "Chocolate": "चॉकलेट",
        "Vanilla": "व्हॅनिला",
        "Choco & Vanilla Mix": "चोको आणि व्हॅनिला मिक्स",
        "Chocolate Dip Softy": "चॉकलेट डिप सॉफ्टी",
        "Vanilla Dip Softy": "व्हॅनिला डिप सॉफ्टी",
        "Choco & Vanilla Mix Dip": "चोको आणि व्हॅनिला मिक्स डिप",
        "Dark Choco Dip Softy": "डार्क चोको डिप सॉफ्टी",
        "Wafer Softy": "वेफर सॉफ्टी",
        "Cold Coffee (Chocolate)": "कोल्ड कॉफी (चॉकलेट)",
        "added": "✓ ऑर्डर केली!",
        "addOrder": "+ ऑर्डर",
        "ourPromise1": "आमचे ",
        "ourPromise2": "वचन",
        "promiseText": "फ्लिजटामध्ये दररोज बनवले जाणारे सोडा अस्सल भारतीय मसाले, ताजी फळे आणि पिढ्यानपिढ्या चालत आलेल्या तंत्रानं तयार केले जातात. अस्सल भारत. 🇮🇳",
        "getToKnowUs": "आमच्याबद्दल जाणून घ्या",
        "footerSubtitle": "भारतातील सर्वात आवडता स्पार्कलिंग सोडा बार — ताज्या पद्धतीनं बनलेला आणि प्रेमाने दिला जातो.",
        "info": "माहिती",
        "franchise": "फ्रेंचायझी",
        "contact": "संपर्क",
        "copyright": "© 2026 Fizztaa Soda Co. प्रेमाने भारतात निर्मित.",
        "privacyPolicy": "गोपनीयता धोरण",
        "termsOfUse": "वापरण्याच्या अटी",
        "fssaiInfo": "FSSAI माहिती",
        
        // Auth
        "signIn": "लॉग इन करा",
        "signUp": "साइन अप करा",
        "fullName": "पूर्ण नाव",
        "phone": "मोबाईल नंबर",
        "email": "ईमेल पत्ता",
        "password": "पासवर्ड",
        "dontHaveAccount": "खाते नाही का?",
        "alreadyHaveAccount": "आधीच खाते आहे का?",
        "welcomeBack": "पुन्हा स्वागत आहे!",
        "createAccount": "खाते तयार करा",
        "loginSuccess": "यशस्वीरित्या लॉग इन केले!",
        "signupSuccess": "खाते यशस्वीरित्या तयार केले!",
        "logoutSuccess": "यशस्वीरित्या लॉग आउट केले!",
        "signToOrder": "ऑर्डर करण्यासाठी लॉग इन करा",
        "editProfile": "प्रोफाईल संपादित करा",
        "saveChanges": "बदलाव जतन करा",
        "profileUpdateSuccess": "प्रोफाईल यशस्वीरित्या अपडेट केली!",
        
        // Orders
        "myCart": "माझी कार्ट",
        "orderHistory": "ऑर्डर इतिहास",
        "orderId": "ऑर्डर आयडी",
        "status": "स्थिती",
        "date": "तारीख",
        "noOrdersYet": "अद्याप एकही ऑर्डर नाही",
        "orderReceived": "ऑर्डर मिळाली",
        "preparing": "तुमचा फिझ तयार होत आहे",
        "outForDelivery": "डिलिव्हरीसाठी बाहेर",
        "delivered": "वितरित केले"
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const getInitialLanguage = () => {
        const savedLang = localStorage.getItem('app_language');
        if (savedLang && translations[savedLang]) {
            return savedLang;
        }
        
        // Check browser settings
        if (navigator.language && navigator.language.toLowerCase().startsWith('mr')) {
            return 'mr';
        }
        if (navigator.language && navigator.language.toLowerCase().startsWith('hi')) {
            return 'hi';
        }
        return 'en';
    };

    const [language, setLanguage] = useState(getInitialLanguage);

    useEffect(() => {
        localStorage.setItem('app_language', language);
        document.documentElement.lang = language;
    }, [language]);

    // This handles automatic browser changes IF the user hasn't explicitly set a custom overriding preference in theory,
    // although tracking system language changes dynamically is less common than dark mode, 
    // window 'languagechange' event handles when a user changes their browser language preferences.
    useEffect(() => {
        const handleLanguageChange = () => {
            if (!localStorage.getItem('app_language')) {
                const newLang = navigator.language.toLowerCase().startsWith('mr') ? 'mr' : (navigator.language.toLowerCase().startsWith('hi') ? 'hi' : 'en');
                setLanguage(newLang);
            }
        };

        window.addEventListener('languagechange', handleLanguageChange);
        return () => window.removeEventListener('languagechange', handleLanguageChange);
    }, []);

    const t = (key) => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
